FROM tier/grouper:2.4.0-a47-u25-w5-p6-20190611

LABEL author="tier-packaging@internet2.edu <tier-packaging@internet2.edu>"

COPY container_files/tmp/* /tmp/
COPY container_files/usr-local-bin/* /usr/local/bin/
