# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63106056cab3bed9411929fee1c8487b05310b655e36196f6ada1fadd4efe1b98a6f09232135177526c660d541fccac960719b8c0d0d10df921c9797cd2e7500

test:
  secret_key_base: 4f9fcebe5a186db5cd843b3538e116be730f8933a50cee964acee4585299575c286fdbd2bfb3b10040c6654faf8e137d1f37390f4f90ccb8ecdc3d02bea45c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
