FROM tier/mariadb:mariadb10

ENV MYSQL_DATABASE registry
ENV MYSQL_USER root
ENV MYSQL_PASSWORD password
ENV MYSQL_DATADIR /var/lib/mysqlmounted
#ENV AFTER_FIRST_TIME_SQL /seed-data/persons-and-courses.sql

