FROM tier/mariadb:mariadb10

ENV MYSQL_DATABASE registry
ENV MYSQL_USER registry_user
ENV MYSQL_PASSWORD 123321
ENV MYSQL_DATADIR /var/lib/mysqlmounted
#ENV AFTER_FIRST_TIME_SQL /seed-data/persons-and-courses.sql

