rabbit_host: tier-demo-rabbit
rabbit_port: 5672
rabbit_user: guest
rabbit_pass: guest
rabbit_exchange: amq.topic
rabbit_routing_key: ref.courses.*
grouper_host: http://tier-demo-grouper:8080
grouper_user: tjordan
grouper_pass: 12345
debug: 1
canvas_url: https://tier.instructure.com
canvas_token: **replace_with_generated_token**
default_password: Password12345
email_suffix: example.edu
courses:
    - CS101
    - CS102
    - TIER101
    - MATH101
    - ACCT101
