version: "3.3"

services:
  mq:
    build: ./mq/
    environment:
     - RABBITMQ_NODENAME=docker-rabbit
    hostname: rabbitmq
    networks:
     - net
    ports:
     - 15672:15672
    volumes:
     - mq:/var/lib/rabbitmq

networks:
  net:    
    driver: bridge

volumes:
  mq:

