server:
  use-forward-headers: true
  forward-headers-strategy: NATIVE
  context-path: /idpui
  servlet:
    context-path: /idpui
  tomcat:
    redirect-context-root: false
  ssl:
    enabled: true
    key-store: /opt/shibui/shibui-test.p12
    key-store-password: testing
    key-store-type: pkcs12
    key-password: testing
  port: 8443
shibui:
  default-password: "{noop}letmein7"
  roles: ROLE_ADMIN,ROLE_NONE,ROLE_USER,ROLE_ENABLE,ROLE_PONY
  metadataProviders:
    target: "file:/generated-config/shibui-metadata-providers.xml"
  metadata-dir: "/generated-metadata"
  beacon-enabled: true
  pac4j-enabled: true
  pac4j:
    keystorePath: "/opt/shibui/saml/samlcert.p12"
    keystoreType: "PKCS12"
    keystorePassword: "changeit"
    privateKeyPassword: "changeit"
    serviceProviderEntityId: "https://sp.example.org/shibui"
    serviceProviderMetadataPath: "/opt/shibui/saml/sp-metadata.xml"
    identityProviderMetadataPath: "/opt/shibui/saml/idp-metadata.xml"
    forceServiceProviderMetadataGeneration: true
    callbackUrl: "https://__CSPHOSTNAME__/idpui/callback"
    maximumAuthenticationLifetime: 3600000
    simpleProfileMapping:
      username: urn:oid:0.9.2342.19200300.100.1.1
      firstname: urn:oid:2.5.4.42
      lastname: urn:oid:2.5.4.4
      email: urn:oid:0.9.2342.19200300.100.1.3
      groups: urn:oid:1.3.6.1.4.1.5923.1.5.1.1     #memberOf
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://idpui-data:5432/shibui
    username: shibui
    password: secret
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    org:
      pac4j:
        saml:
          crypto: DEBUG
      opensaml:
        security:
          credential: DEBUG
        xmlsec:
          encryption:
            support: DEBUG
      apache:
        xml:
          security:
            encryption: DEBUG

