server:
  context-path: /idpui
  servlet:
    context-path: /idpui
  tomcat:
    redirect-context-root: false
  ssl:
    enabled: true
    key-store: /opt/shibui/shibui-test.p12
    key-store-password: testing
    key-store-type: pkcs12
    key-password: testing
  port: 8443
shibui:
  default-password: "{noop}letmein7"
  metadataProviders:
    target: "file:/generated-config/shibui-metadata-providers.xml"
  metadata-dir: "/generated-metadata"
  beacon-enabled: true
  pac4j-enabled: false
  pac4j:
    keystorePath: "/opt/shibui/saml/samlkeystore.jks"
    keystorePassword: "changeit"
    privateKeyPassword: "changeit"
    serviceProviderEntityId: "https://sp.example.org/shibui"
    serviceProviderMetadataPath: "/opt/shibui/saml/sp-metadata.xml"
    identityProviderMetadataPath: "/opt/shibui/saml/idp-metadata.xml"
    forceServiceProviderMetadataGeneration: false
    callbackUrl: "https://__CSPHOSTNAME__/idpui/callback"
    maximumAuthenticationLifetime: 3600000
    saml2ProfileMapping:
      username: urn:oid:0.9.2342.19200300.100.1.1
      firstname: urn:oid:2.5.4.42
      lastname: urn:oid:2.5.4.4
      email: urn:oid:0.9.2342.19200300.100.1.3
spring:
  datasource:
    username: shibui
    password: secret
    url: jdbc:mariadb://idpui-data:3306/shibui
    driverClassName: org.mariadb.jdbc.Driver
    platform: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

     