version: "3.3"

services:
  grouper_daemon:
    build: ./grouper_daemon/
    command: bash -c "while ! curl -s grouper_data:3306 > /dev/null; do echo waiting for mysql on grouper_data to start; sleep 3; done; while ! curl -s ldap://directory:389 > /dev/null; do echo waiting for ldap on directory to start; sleep 3; done; exec daemon"
    depends_on:
     - grouper_data
     - directory
    environment:
     - ENV
     - USERTOKEN
     - GROUPER_CLIENT_WEBSERVICE_PASSWORD_FILE=password
     - GROUPER_DATABASE_PASSWORD_FILE=/run/secrets/g_database_password.txt
     - RABBITMQ_PASSWORD_FILE=/run/secrets/rabbitmq_password.txt
     - SUBJECT_SOURCE_LDAP_PASSWORD=password
    networks:
      net:
        aliases:
         - grouper-daemon
    secrets:
     - g_database_password.txt
     - rabbitmq_password.txt
     - source: grouper.hibernate.properties
       target: grouper_grouper.hibernate.properties
     - source: grouper-loader.properties
       target: grouper_grouper-loader.properties
     - source: subject.properties
       target: grouper_subject.properties
    volumes:
     - type: bind
       source: ./configs-and-secrets/grouper/application/grouper.properties
       target: /opt/grouper/conf/grouper.properties
     - type: bind
       source: ./configs-and-secrets/grouper/application/grouper.client.properties
       target: /opt/grouper/conf/grouper.client.properties

  grouper_ui:
    build: ./grouper_ui/
    command: bash -c "while ! curl -s grouper_data:3306 > /dev/null; do echo waiting for mysql on grouper_data to start; sleep 3; done; while ! curl -s ldap://directory:389 > /dev/null; do echo waiting for ldap on directory to start; sleep 3; done; exec ui"
    depends_on:
     - grouper_data
     - directory
    environment:
     - ENV
     - USERTOKEN
     - GROUPER_DATABASE_PASSWORD_FILE=/run/secrets/g_database_password.txt
     - SUBJECT_SOURCE_LDAP_PASSWORD=password
    networks:
      net:
        aliases:
         - grouper-ui
    ports:
     - 4443:443
    secrets:
     - g_database_password.txt
     - source: grouper.hibernate.properties
       target: grouper_grouper.hibernate.properties
     - source: grouper-loader.properties
       target: grouper_grouper-loader.properties
     - source: subject.properties
       target: grouper_subject.properties
     - source: g_sp-key.pem
       target: shib_sp-key.pem
     - source: g_host-key.pem
       target: host-key.pem
    volumes:
     - type: bind
       source: ./configs-and-secrets/grouper/application/grouper.properties
       target: /opt/grouper/conf/grouper.properties
     - type: bind
       source: ./configs-and-secrets/grouper/application/grouper.client.properties
       target: /opt/grouper/conf/grouper.client.properties
     - type: bind
       source: ./configs-and-secrets/grouper/shibboleth/sp-cert.pem
       target: /etc/shibboleth/sp-cert.pem
     - type: bind
       source: ./configs-and-secrets/grouper/shibboleth/shibboleth2.xml
       target: /etc/shibboleth/shibboleth2.xml
     - type: bind
       source: ./configs-and-secrets/grouper/shibboleth/idp-metadata.xml
       target: /etc/shibboleth/idp-metadata.xml
     - type: bind
       source: ./configs-and-secrets/grouper/httpd/host-cert.pem
       target: /etc/pki/tls/certs/host-cert.pem
     - type: bind
       source: ./configs-and-secrets/grouper/httpd/host-cert.pem
       target: /etc/pki/tls/certs/cachain.pem

  grouper_ws:
    build: ./grouper_ws/
    command: bash -c "while ! curl -s grouper_data:3306 > /dev/null; do echo waiting for mysql to start; sleep 3; done; while ! curl -s ldap://directory:389 > /dev/null; do echo waiting for ldap to start; sleep 3; done; exec ws"
    depends_on:
     - grouper_data
     - directory
    environment:
     - ENV
     - GROUPER_DATABASE_PASSWORD_FILE=/run/secrets/g_database_password.txt
     - SUBJECT_SOURCE_LDAP_PASSWORD=password
     - USERTOKEN
    networks:
      net:
        aliases:
         - grouper-ws
    ports:
     - 9443:443
    secrets:
     - g_database_password.txt
     - source: grouper.hibernate.properties
       target: grouper_grouper.hibernate.properties
     - source: grouper-loader.properties
       target: grouper_grouper-loader.properties
     - source: subject.properties
       target: grouper_subject.properties
     - source: g_sp-key.pem
       target: shib_sp-key.pem
     - source: g_host-key.pem
       target: host-key.pem
    volumes:
     - type: bind
       source: ./configs-and-secrets/grouper/application/grouper.properties
       target: /opt/grouper/conf/grouper.properties
     - type: bind
       source: ./configs-and-secrets/grouper/application/grouper.client.properties
       target: /opt/grouper/conf/grouper.client.properties
     - type: bind
       source: ./configs-and-secrets/grouper/httpd/host-cert.pem
       target: /etc/pki/tls/certs/host-cert.pem
     - type: bind
       source: ./configs-and-secrets/grouper/httpd/host-cert.pem
       target: /etc/pki/tls/certs/cachain.pem

  grouper_data:
    build: ./grouper_data/
    networks:
      net:
        aliases:
         - grouper-data
    ports:
     - 3306:3306
    volumes:
     - grouper_data:/var/lib/mysql  

  directory:
    build: ./directory/
    ports:
     - 389:389
    networks:
     - net
    volumes:
     - ldap:/var/lib/dirsrv

  sources:
    build: ./sources/
    ports:
     - 13306:3306
    networks:
     - net
    volumes:
     - source_data:/var/lib/mysql

  targets:
    build: ./targets/
    ports:
     - 23306:389
    networks:
     - net
    volumes:
     - target_data:/var/lib/mysql

  midpoint_data:
    image: tier/mariadb:mariadb10
    ports:
     - 33306:3306
    networks:
      net:
        aliases:
         - midpoint-data
    volumes:
     - midpoint_mysql:/var/lib/mysql
     - midpoint_data:/var/lib/mysqlmounted
    environment:
     - CREATE_NEW_DATABASE=if_needed

  midpoint_server:
    build: ./midpoint_server/
    depends_on:
     - midpoint_data
    ports:
     - 8443:443
    environment:
     - AUTHENTICATION
     - ENV
     - USERTOKEN
     - REPO_DATABASE_TYPE
     - REPO_JDBC_URL
     - REPO_HOST
     - REPO_PORT
     - REPO_DATABASE
     - REPO_USER
     - REPO_MISSING_SCHEMA_ACTION
     - REPO_UPGRADEABLE_SCHEMA_ACTION
     - REPO_SCHEMA_VERSION_IF_MISSING
     - REPO_SCHEMA_VARIANT
     - MP_MEM_MAX
     - MP_MEM_INIT
     - MP_JAVA_OPTS
     - SSO_HEADER
     - TIER_BEACON_OPT_OUT
     - TIMEZONE
    networks:
      net:
        aliases:
         - midpoint-server
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
     - mp_sp-encrypt-key.pem
     - mp_sp-signing-key.pem
     - mp_host-key.pem
    volumes:
     - midpoint_home:/opt/midpoint/var
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/shibboleth2.xml
       target: /etc/shibboleth/shibboleth2.xml
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/idp-metadata.xml
       target: /etc/shibboleth/idp-metadata.xml
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/sp-signing-cert.pem
       target: /etc/shibboleth/sp-signing-cert.pem
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/sp-encrypt-cert.pem
       target: /etc/shibboleth/sp-encrypt-cert.pem
     - type: bind
       source: ./configs-and-secrets/midpoint/httpd/host-cert.pem
       target: /etc/pki/tls/certs/host-cert.pem
     - type: bind
       source: ./configs-and-secrets/midpoint/httpd/host-cert.pem
       target: /etc/pki/tls/certs/cachain.pem

  idp:
    build: ./idp/
    depends_on:
     - directory
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    networks:
     - net
    ports:
     - 443:443

  mq:
    build: ./mq/
    environment:
     - RABBITMQ_NODENAME=docker-rabbit
    hostname: rabbitmq
    networks:
     - net
    ports:
     - 15672:15672
    volumes:
     - mq:/var/lib/rabbitmq

networks:
  net:    
    driver: bridge

secrets:
# grouper
  g_host-key.pem:
    file: ./configs-and-secrets/grouper/httpd/host-key.pem
  g_sp-key.pem:
    file: ./configs-and-secrets/grouper/shibboleth/sp-key.pem
  g_database_password.txt:
    file: ./configs-and-secrets/grouper/application/database_password.txt
  rabbitmq_password.txt:
    file: ./configs-and-secrets/grouper/application/rabbitmq_password.txt
  grouper.hibernate.properties:
    file: ./configs-and-secrets/grouper/application/grouper.hibernate.properties
  grouper-loader.properties:
    file: ./configs-and-secrets/grouper/application/grouper-loader.properties
  subject.properties:
    file: ./configs-and-secrets/grouper/application/subject.properties
# midPoint
  mp_host-key.pem:
    file: ./configs-and-secrets/midpoint/httpd/host-key.pem
  mp_sp-signing-key.pem:
    file: ./configs-and-secrets/midpoint/shibboleth/sp-signing-key.pem
  mp_sp-encrypt-key.pem:
    file: ./configs-and-secrets/midpoint/shibboleth/sp-encrypt-key.pem
  mp_database_password.txt:
    file: ./configs-and-secrets/midpoint/application/database_password.txt
  mp_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/application/keystore_password.txt    
    
volumes:
  grouper_data:
  source_data:
  target_data:
  ldap:
  midpoint_data:
  midpoint_mysql:
  midpoint_home:
  mq:
