version: "3.3"

services:

  wordpress_server:
    build: ./wordpress_server/
    container_name: wordpress_server
    networks:
      - wordpress_net
    depends_on:
      - wordpress_data
    command: bash -c 'if [ ! -s /var/www/html/wp-config.php ];  then /root/wp core download --allow-root; sleep 10; /root/wp config create --dbname=wordpress --dbuser=wordpress --dbpass=54y6RxN7GfC7aes3 --dbhost=wordpress_data --allow-root; sleep 3; /root/wp core install --url="http://localhost/" --title="wordpress" --admin_user="admin" --admin_password="54y6RxN7GfC7aes3" --admin_email="sentrifugo.container@gmail.com" --allow-root; /root/wp --allow-root rewrite structure "/%postname%" --hard --debug; /root/wp  rewrite flush --hard --debug --allow-root; sed -i "s/<\/IfModule>/RewriteCond \%{HTTP:Authorization} \^\(\.\*\)\nRewriteRule \^\(\.\*\) - [E=HTTP_AUTHORIZATION:\%1]\n<\/IfModule>\nSetEnvIf Authorization "\(\.\*\)" HTTP_AUTHORIZATION=\$$1/" /var/www/html/.htaccess; /root/sed.sh; /root/wp plugin install jwt-authentication-for-wp-rest-api  --activate --allow-root; /root/wp plugin install wp-rest-api-log --activate --allow-root; /root/wp plugin install shibboleth --activate --allow-root; fi; /usr/local/bin/startup.sh;'
    ports:
      - "80:80"
    devices:
      - "/dev/tty:/dev/tty"
    volumes:
      - wordpress_server:/var/www/html

  wordpress_data:
    build: ./wordpress_data/
    container_name: wordpress_data
    networks:
      - wordpress_net
    volumes:
      - wordpress_data:/var/lib/mysql
    ports:
      - 3306

networks:
  wordpress_net:
    driver: bridge
    
volumes:
  wordpress_data:
  wordpress_server:

