version: '2'

services:
  sis-db:
    image: mysql:5.6
    container_name: tier-demo-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  sis-web:
    build: .
    image: sis-web
    container_name: tier-sis-web
    command: /bin/bash /usr/local/bin/run-rails.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - sis-db
      - sis-rabbit
    environment:
      - RABBITMQ_URI=amqp://tier-demo-rabbit
  sis-rabbit:
    image: rabbitmq:3-management
    container_name: tier-demo-rabbit
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672
